### ISSUE TITLE
Add a grafana dashboard

### ISSUE THREAD

**Issue by MatthiasVervaet** [tigrisdata/fdb-exporter#29]
Big thanks for this prometheus exporter. Are you willing to share a grafana dashboard for these metrics?

**Comment by pboros** [comment]
Hey, I just added what we are using to the dashboards folder, check it out. We only started using grafana recently, and as you can see, my dashboard building skills could be improved. If you make it better looking, feel free to issue a pull request.

**Comment by MatthiasVervaet** [comment]
Thank you! We also created a Grafana dashboard in the meantime, i will have a look at your solution and see if we can contribute to this repo.

**Comment by pboros** [comment]
Sounds great, pull requests are welcome. Happy to include your dashboard as well, we can also combine forces. Sorry for the late responses, I pay more attention to the issues of this project. I am super happy that it was useful to someone else as well.
